### ISSUE TITLE
Provide capability to exclude API endpoints for request tracking

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.webapi#200]
**Is your feature request related to a problem? Please describe.**
Provide the capability to exclude API endpoints for request tracking since they might not be relevant, or you want to optimize the cost for all your telemetry.

In some cases; you'd like to filter all requests while for others you might want to filter them out based on the status code.

**Describe the solution you'd like**
I'd love to have flexibility in the sense that:
- I can apply an attribute on my operation to opt-out for tracking
  - Would be nice to have optional flags there to give granularity to only opt-out for request, response or both
  - Provide an optional flag to define what status codes should be tracked, all that are not specified are considered to be excluded
- Same as above, but through the request logging options instead

That said, I personally, would be fine if we start with attributes only since describing all of this through the options would be either hard or verbose and not really what we would use I think

**Comment by stijnmoreels** [comment]
### Attributes
- [x] Exclude request tracking #202 
- [ ] Exclude response tracking
    - [ ] Specify status codes which are to be tracked 
- [ ] Exclude request & response tracking  

### Options
- [ ] Exclude request tracking alltogheter
- [ ] Exclude response tracking alltogether
    - [ ] Specify which status codes should be tracked
- [ ] Exclude request & response tracking

Question though, why should you have an option that exclude request and response tracking in the options? If you don't use it alltogheter, why specify it?
